#!/usr/bin/env bash
# A script that configures an Ubuntu server with the below requirements.

sudo sed -i '/127\.0\.0\.1\s\+/localhost/d' /etc/hosts
sudo sed -i '/facebook\.com/d' /etc/hosts

echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
